### PR TITLE
Add support for using categories as hashtags on posts

### PR DESCRIPTION
**Pull request by rseabra**
Hi,

In my usage of Mastodon_Autopost I came across the need to use categories as my hashtags.
Considering this could be useful for others, I propose this code change in order to add that useful feature.

Best regards,
Rui

### CODE REVIEW

**Comment by rseabra** [comment]
I'm unsure if I should have rather used ->slug instead of ->name, as names may have spaces and the result is concatenated strings making it ugly, but I'm not sure if - is a valid character for tags anyway.

**Comment by rseabra** [comment]
I just confirmed that - is not a valid character, so better leave it like it is, IMHO.

**Comment by simonfrey** [comment]
Thanks for your help here! Will be updated in the plugin in a few minutes!

**Comment by rseabra** [comment]
Yay, thanks! :)

**Pull request merged**
