### PR TITLE
Strip non-alphanumeric characters and capitalize words in hashtags

### LINKED ISSUE #63: Each word in hashtags should be capitalized
The plugin only capitalizes the first word when converting tags and categories into hashtags. For accessibility reasons, each word in the hashtag should be capitalized. For example, if there's a tag or category called "information security", then the hashtag should be "#InformationSecurity", not "#Informationsecurity".

### PR DESCRIPTION
**Pull request by jikamens**
Fixes #63.

Untested, but I think this is correct.

### CODE REVIEW

**Comment by numeratorjik** [comment]
Anybody here? ;-)

**Comment by simonfrey** [comment]
Could you please test it before we continue here :) Not that it explode into out faces

**Comment by jikamens** [comment]
I would like to test but it looks like the version of the plugin here is 3.6.1 whereas the version of the plugin in the plugin repository is 3.6.6. Is there another repository somewhere else I should be using instead of this one? I want to test my change against the current version of the plugin, not against an obsolete version.

**Comment by jikamens** [comment]
Ping. Can someone answer the comment above?

**Comment by jikamens** [comment]
For what it's worth, I found the source code at https://plugins.svn.wordpress.org/autopost-to-mastodon/trunk and confirmed that my patches in this PR apply cleanly to 3.6.7 and work properly in production (i.e., I tested them, they work).
I built a git repo with git-svn and pushed my changes to it in https://github.com/jikamens/autopost-to-mastodon/tree/fixup_hashtags. The two commits on that branch apply cleanly to the SVN code base. They fix one whitespace error introduced by the first patch in this PR, but aside from that they are identical.
Any chance of getting them merged?

**Comment by simonfrey** [comment]
Should work. Thanks for your help :)

**Pull request merged**
